glmsingle:
  design_matrix:
    n_features: 4358  # number of possible features across sessions - upper bound: final dm only contains used features
  data:
    datatype: 'T1W'
    nordictype: 'nordicstc'
  model:
    wantlibrary: 1
    wantfracridge: 1
    wantglmdenoise: 1
    wantfileoutputs: [1, 1, 1, 1]
  fit:
    stimdur: 2.5
    tr: 0.9
motion_energy:
  size: [160, 240]
  fps: 24
fracridge:
  threshold: .4 # if int: top N voxels, if float: all voxels with R2 > N
  cv: 5
prf:
  design_matrix:
    vhsize: [512, 512]
    tr_canonical: .06667  # 15 fps
    tr_output: .9  # tr used in acquisition
    gif_speed: 100  # real-time = 1
  fit:
    screen_size_cm: 40
    screen_distance_cm: 200


paths:
  stimuli: '/tank/shared/2024/visual/AOT/derivatives/stimuli/rescaled_final'
  data: '/tank/shared/2024/visual/AOT/derivatives/fmripreps/aotfull_preprocs/fullpreproc_forcesyn'
  motion_energy: './motion_energy_features'
  derivatives: './derivatives'
  aot_experiment: 
    base: './arrow_of_time_experiment'
    settings: 'aot/data/experiment/settings/main'
  prf_experiment:
    base: './prf_experiment'
    input: 'logs'
    design: 'stimuli'
    bold: '/tank/shared/2024/visual/AOT/temp/prftest/psc_average/'
