glmsingle:
  design_matrix:
    n_features: 4358  # number of possible features across sessions - upper bound: final dm only contains used features
  data:
    datatype: 'T1W'
    nordictype: 'nordicstc'
  model:
    wantlibrary: 1
    wantfracridge: 1
    wantglmdenoise: 1
    wantfileoutputs: [1, 1, 1, 1]
  fit:
    stimdur: 2.5
    tr: 0.9
motion_energy:
  vhsize: [160, 240]
  fps: 24
fracridge:
  threshold: .4 # if int: top threshold voxels, if float: all voxels with R2 > threshold
  cv: 5
prf:
  design_matrix:
    blank: -1
    vhsize_canonical: [512, 512]
    vhsize_output: [128, 128]
    tr_canonical: .066667  # stimulus tr
    tr_output: .9  # data tr
    gif_speed: 100  # real-time = 1
  fit:
    rsq_threshold: .1

    # fitting tolerance
    xtol: 0.00001
    ftol: 0.00001
    
    # visual field
    screen_size_cm: 40
    screen_distance_cm: 200
    vf_extent: [-5, 5]
    vhsize: [160, 240]

    # define search spaces
    hrf:
      default: [1,1,0]  # not used if fitted
      deriv_bound: [0,10]
      disp_bound: [0,0]
      normalize_hrf: True
      normalize_rf: False

    amplitude:
      bold_bsl: [0,0] # [-60,60] original, then [0,1000]
      prf_ampl_gauss: [-80,80] #pos_prf would be [0, 1000]??  original = [-80,80]
      prf_ampl_norm: [0,1000]
      css_exponent: [0.01,3]
    gaussian_gridpoints: 30
    dn:
      surround_amplitude_grid: [0.05,0.2,0.4,0.7,1,3]
      surround_size_grid: [3,5,8,12,18]
      neural_baseline_grid: [0,1,10,100]
      surround_baseline_grid: [0.1,1.0,10.0,100.0] # [1]
      surround_amplitude_bound: [0,1000]
      neural_baseline_bound: [0,1000]
      surround_baseline_bound: [1e-6,1000] # [1]


    


paths:
  stimuli: '/tank/shared/2024/visual/AOT/derivatives/stimuli/rescaled_final'
  data: '/tank/shared/2024/visual/AOT/derivatives/fmripreps/aotfull_preprocs/fullpreproc_forcesyn'
  motion_energy: './motion_energy_features'
  derivatives: './derivatives'
  aot_experiment: 
    base: './arrow_of_time_experiment'
    settings: 'aot/data/experiment/settings/main'
  prf_experiment:
    base: './prf_experiment'
    input: 'logs'
    design: 'stimuli'
    bold: '/tank/shared/2024/visual/AOT/temp/prftest/psc_average/'
