motion_energy:
  size: [160, 240]
  fps: 24
glmsingle:
  datatype: 'T1W'
  nordictype: 'nordicstc'
  stimdur: 2.5
  tr: 0.9
  params:
    wantlibrary: 1
    wantfracridge: 1
    wantglmdenoise: 1
    wantfileoutputs: [1, 1, 1, 1]

paths:
  stimuli: '/tank/shared/2024/visual/AOT/derivatives/stimuli/rescaled_final'
  data: '/tank/shared/2024/visual/AOT/derivatives/fmripreps/aotfull_preprocs/fullpreproc1'
  motion_energy: './motion_energy_features'
  derivatives: './derivatives'
