glmsingle:
  input:
    datatype: 'T1W'
    nordictype: 'nordicstc'
  model:
    wantlibrary: 1
    wantfracridge: 1
    wantglmdenoise: 1
    wantfileoutputs: [1, 1, 1, 1]
  fit:
    stimdur: 2.5
    tr: 0.9
motion_energy:
  size: [160, 240]
  fps: 24
fracridge:
  threshold: 100
prf_experiment:
  tr: .0667  # defines temporal resolution
  vhsize: [512, 512]


paths:
  stimuli: '/tank/shared/2024/visual/AOT/derivatives/stimuli/rescaled_final'
  data: '/tank/shared/2024/visual/AOT/derivatives/fmripreps/aotfull_preprocs/fullpreproc1'
  motion_energy: './motion_energy_features'
  derivatives: './derivatives'
  prf_experiment:
    base: './prf_experiment'
    input: 'logs'
    output: 'stimuli'
